# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hellov' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  # Pods for Hellov
  pod 'FBSDKCoreKit', '4.38'
  pod 'FBSDKLoginKit', '4.38'
  pod 'FBSDKShareKit', '4.38'
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core', '6.2.0'
  pod 'Firebase/Messaging', '6.2.0'
  pod 'Firebase/Analytics', '6.2.0'
  pod 'RSKImageCropper'

end
